### ISSUE TITLE
Please add option to add background image to certain section.

### ISSUE THREAD

**Issue by nooralam6** [accatyyc/JEKScrollableSectionCollectionViewLayout#4]
It's awesome layout for collection view, please add methods to add the background image and colour or gradient to add on certain sections.

**Comment by accatyyc** [comment]
Hi, thanks for the suggestion!

It should be fairly simple to create a subclass that adds a supplementary view type for a section background. I'll consider making it part of this project!

**Comment by accatyyc** [comment]
Yeah, I understood what you mean. I meant that this is a good use case for supplementary views too. You just add another kind, so you have headers, footers and section background supplementary views.

**Comment by accatyyc** [comment]
Hey again, I implemented an example of this in 27da480. Could you try it out and see if it solves your problem? To test it, point the pod to master and run `pod install`:

```pod 'JEKScrollableSectionCollectionViewLayout, :git => 'https://github.com/accatyyc/JEKScrollableSectionCollectionViewLayout.git', :branch => 'master'```

Then, when setting up your layout, do the following:

```objc
// Register a class to use as background views
[self.collectionView registerClass:[UICollectionReusableView class] forSupplementaryViewOfKind:JEKCollectionElementKindSectionBackground withReuseIdentifier:@"backgroundView"];

// Enable background views in the layout object
layout.showsSectionBackgrounds = YES;
```

Then implement `viewForSupplementaryElementOfKind:` normally, but add an extra check to create background views:

```objc
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath {
    // .... header and footer code here
        } else if (kind == JEKCollectionElementKindSectionBackground) {
        UICollectionReusableView *view = [collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:@"backgroundView" forIndexPath:indexPath];
        view.backgroundColor = UIColor.redColor;
        return view;
    }
}
```

Let me know if this solves your problem!

**Comment by nooralam6** [comment]
Hey,
It works! 
Thank you so much for the wonderful work you are doing!
Keep it up.

**Comment by accatyyc** [comment]
Great! This will be released with the next version, within a day or so, so you can keep tracking the official releases in your podfile again.

**Comment by accatyyc** [comment]
Added in [v1.1.0](https://github.com/accatyyc/JEKScrollableSectionCollectionViewLayout/releases/tag/v1.1.0)
