### ISSUE TITLE
empty sections title are build on each other

### ISSUE THREAD

**Issue by OfirMalach** [accatyyc/JEKScrollableSectionCollectionViewLayout#7]
**For empty sections**, I'm trying to **keep headers visible**.
each section header goes on each other

filled items:
![img_0407](https://user-images.githubusercontent.com/5443605/50396760-9346c400-0774-11e9-8e4e-4a65d26f1dde.png)

empty items (issue):
![img_0406](https://user-images.githubusercontent.com/5443605/50396763-9772e180-0774-11e9-8ecf-350b32d0d749.png)

Is it possible to fix it?

**Comment by accatyyc** [comment]
Hi, thanks for the bug report! I fixed this in `v1.1.1` which should be available with a pod update. Let me know if it doesn't work.
