### ISSUE TITLE
Swift Version 

### ISSUE THREAD

**Issue by willysharp5** [accatyyc/JEKScrollableSectionCollectionViewLayout#9]
Great Library. 
Could you show how this can be used with Swift, maybe sample code would be nice. 

Thanks

**Comment by accatyyc** [comment]
Hi! The example project should be pretty easy to convert to Swift, but I can probably rewrite it in Swift if that would help.

**Comment by willysharp5** [comment]
That would be great.

**Comment by accatyyc** [comment]
I added an example in the README in Swift. Let me know if there's anything else you'd like to see in it!
